# Generated by Django 4.2.7 on 2026-08-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('at_hub', 'Arrived at Hub'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipmentstatushistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Pickup'), ('picked_up', 'Picked Up'), ('at_hub', 'Arrived at Hub'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_description', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_requests', to='shipments.customer')),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_requests', to='shipments.address')),
                ('pickup_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_requests', to='shipments.address')),
                ('shipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_request', to='shipments.shipment')),
            ],
        ),
    ]
